name: soul Attack

on:
  push:
    branches: [ main ]
  schedule:
    # Triggers every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  soul:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # 17 parallel instances
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
      fail-fast: false

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        pip install python-telegram-bot PyGithub

    - name: Run Soul for 2 Hours
      run: |
        chmod +x soul vickyisonlive.py
        # 'timeout 2h' will stop the script after 120 minutes
        timeout 2h python3 soul.py || echo "Job timed out as planned"
